### ISSUE TITLE
Make `FileCleaner` utility class

### ISSUE THREAD

**Issue by tirth132** [tirth132/mine#1]
Add a class called `FileCleaner`. It should be an utility class which should provide static methods for file cleaning processes.

The class should provide method by which we can delete all files inside a directory. This must not delete whole directory anyway, as this may be used to delete cache files or temporary files.

**Comment by Krish-bhardwaj** [comment]
Hi i am a fresher looking for some opensource contribution can u help me out i want to contribute to your project i have decent experience with java programing language,  and can u assign me this issue :)

**Comment by tirth132** [comment]
This feature must not be the part of v0.2.0 release. So I am closing this issue temporally. I will reopen the issue in feature.
